version: '3.8'
services:

  vproapp:
    build:
      context: ./Docker-files/app
    image: vprofileapp
    container_name: vproapp
    volumes:
      - vproappdata:/usr/local/tomcat/webapp
    ports:
      - "8080:8080"


  vprodb:
    build:
      context: ./Docker-files/db
    image: vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproweb:
    build:
      context: ./Docker-files/web
    image: vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
